### ISSUE TITLE
Request: Bring back code snippets

### ISSUE THREAD

**Issue by GeorgeWL** [uidotdev/usehooks#260] opened 2023-11-03 16:02 UTC
So often installing was just not needed for the smaller hooks, so it was nice back when each hook also had the code snippet so one could just copy that instead of installing a whole module.

Can you bring these back?

**Comment by tylermcginnis** [comment] 2023-11-03 17:13
Duplicate of #243

**Closed as completed by tylermcginnis** 2023-11-03 17:13 UTC
