### ISSUE TITLE
Error: useSessionStorage is a client-only hook

### ISSUE THREAD

**Issue by reekrd** [uidotdev/usehooks#284] opened 2024-03-08 07:27 UTC
I'm importing useSessionStorage into a client component but get the error : useSessionStorage is a client-only hook

This happens during build thus the project can't be built. 

And during development. My requested page gets a 500 error but still renders in the browser and data is set in the session storage.

Minimal reproduction can be found here: [https://github.com/reekrd/min-rep-client-only-hook/](https://github.com/reekrd/min-rep-client-only-hook/)

**Comment by mehamednews** [comment] 2024-03-10 13:18
same error when using `useLocalStorage`

**Comment by JuventinoLVH** [comment] 2024-03-12 18:45
This is a duplicate of https://github.com/uidotdev/usehooks/issues/218

As said in https://github.com/uidotdev/usehooks/issues/254#issuecomment-1776358241  'use client' not always run on the client.

**Closed as completed** 2024-03-13 16:27 UTC
